input {
  type:touchpad {
     tap enabled
     dwt enabled
     middle_emulation enabled
     scroll_method two_finger
     drag enabled
     drag_lock enabled
  }

  type:keyboard {
     xkb_layout "latam"
  }
}

