set {
  # @Mod key
  $mod Mod4

  # @Apps
  $term foot
  $menu fuzzel
  $browser zen-browser
  $file nautilus
  
  # @Scripts
  $lock bash $HOME/.config/sway/scripts/lock.sh
  $volume bash $HOME/.config/sway/scripts/volume.sh
  $brightness bash $HOME/.config/sway/scripts/brightness.sh
  $screenshot bash $HOME/.config/sway/scripts/screenshot.sh
  $autostart bash $HOME/.config/sway/scripts/autostart.sh

  # @Home row direction
  $left h
  $down j
  $up k
  $right l

  # @Colors - Frutiger Aero
  $bg-color            #D9E4EC   
  $inactive-bg-color   #D9E4EC
  $text-color          #0B192C  
  $inactive-text-color #7A8B99 
  $urgent-bg-color     #FF6B6B
  $accent-color        #00A8E8
  $overlay-bg-color    #7ED5EA
}
