# @Volume
bindsym XF86AudioRaiseVolume exec $volume up
bindsym XF86AudioLowerVolume exec $volume down
bindsym XF86AudioMute exec $volume mute

# @Microphone
bindsym XF86AudioMicMute exec $volume mic-mute

# @Brightness
bindsym XF86MonBrightnessUp exec $brightness up
bindsym XF86MonBrightnessDown exec $brightness down

# @Screenshots
bindsym Print exec $screenshot full
bindsym $mod+Shift+s exec $screenshot selection
