# @gaps
#smart_gaps on
gaps {
  inner 10px
  outer 25px
}

# @border
default_border pixel 2px
default_floating_border pixel 2px

#                       border          bg         text               indicator          child_border
client.focused          $accent-color   $bg-color  $text-color        $accent-color      $accent-color
client.focused_inactive $overlay-bg-color $bg-color $inactive-text-color $overlay-bg-color $overlay-bg-color
client.unfocused        $bg-color       $bg-color  $inactive-text-color $bg-color        $bg-color
client.urgent           $urgent-bg-color $bg-color $urgent-bg-color   $urgent-bg-color   $urgent-bg-color
client.placeholder      $overlay-bg-color $bg-color $text-color       $overlay-bg-color  $overlay-bg-color
